// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package modelg

import (
	"github.com/go-sdk/database/dbx/datatype"
	"gorm.io/cli/gorm/field"
)

var User = struct {
	Id        field.String
	CreatedBy field.String
	CreatedAt field.Time
	UpdatedBy field.String
	UpdatedAt field.Time
	DeletedAt field.Field[datatype.DeletedAt]
	Name      field.String
	Email     field.String
	Extra     field.Field[datatype.JSON]
}{
	Id:        field.String{}.WithColumn("id"),
	CreatedBy: field.String{}.WithColumn("created_by"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedBy: field.String{}.WithColumn("updated_by"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[datatype.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	Email:     field.String{}.WithColumn("email"),
	Extra:     field.Field[datatype.JSON]{}.WithColumn("extra"),
}
